const KEY='trailos_v2';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
const racesSeed=[
{name:'Trail de Venerque',distance:20,date:'2026-09-06',elevation:450,role:'Course de préparation · vitesse / relance'},
{name:'Trail des Petites Pyrénées — La Graillouteuse',distance:35,date:'2026-10-04',elevation:1000,role:'Répétition générale · inscrit'},
{name:'Trail des Hérétiques',distance:63,date:'2026-10-24',elevation:2750,role:'Objectif automne · top 25 %'},
{name:'Trail 100 Andorra by UTMB',distance:80,date:'2027-06-11',elevation:3900,role:'Objectif principal 2027'}
];

const weeks=[
{title:'31 août – 6 sept.',focus:'Affûtage Venerque : fraîcheur > volume. On garde un peu de vitesse sans créer de fatigue.',sessions:[
['Lun 31','Repos + mobilité','15 min hanches / chevilles / mollets.','Repos'],['Mar 1','Endurance + lignes droites','45 min facile + 5 × 20 s dynamique, récupération complète.','Facile'],['Mer 2','Renfo activation','25–30 min : gainage, moyen fessier, mollets, step-down léger.','Renfo'],['Jeu 3','Rappel allure course','15 min facile + 3 × 3 min RPE 7/10, récup 2 min + retour au calme.','Qualité'],['Ven 4','Repos','Sommeil et hydratation normale.','Repos'],['Sam 5','Réveil musculaire','20–25 min très facile + 4 × 15 s.','Facile'],['Dim 6','TRAIL DE VENERQUE — 20K','Départ contrôlé. Si genou OK après mi-course : progression.','Course']]},
{title:'7 – 13 sept.',focus:'Récupérer de Venerque puis relancer progressivement le volume.',sessions:[['Lun 7','Repos complet','Marche douce uniquement.','Repos'],['Mar 8','Récupération','35–40 min très facile si jambes correctes.','Facile'],['Mer 9','Renforcement','35 min : split squat, step-down, hip thrust, mollets, gainage.','Renfo'],['Jeu 10','Endurance','45 min facile, terrain souple.','Facile'],['Sam 12','Côtes contrôlées','50–60 min avec 8 × 60 s en côte RPE 7/10. Descente lente.','Qualité'],['Dim 13','Sortie longue','1 h 45 à 2 h trail facile, 400–600 m D+ si possible. Tester 60–65 g/h.','Longue']]},
{title:'14 – 20 sept.',focus:'Première vraie semaine spécifique : endurance musculaire + côtes longues.',sessions:[['Lun 14','Repos / mobilité','15 min.','Repos'],['Mar 15','Endurance','45 min facile.','Facile'],['Mer 16','Renforcement lourd contrôlé','35–40 min : 3 séries principales, accent excentrique quadriceps + fessiers.','Renfo'],['Jeu 17','Côtes longues','15 min + 5 × 4 min RPE 7/10, récup en descente facile + 10 min.','Qualité'],['Sam 19','Footing vallonné','60 min facile + 6 × 20 s.','Facile'],['Dim 20','Sortie longue spécifique','2 h 30 à 2 h 45, viser 700–900 m D+. 65 g/h. Finir encore propre.','Longue']]},
{title:'21 – 27 sept.',focus:'Semaine de charge maximale avant la répétition générale, mais sans séance héroïque.',sessions:[['Lun 21','Repos','Sommeil prioritaire.','Repos'],['Mar 22','Tempo trail','45 min max : 15 min facile + 2 × 10 min RPE 6–7 + retour calme.','Qualité'],['Mer 23','Renforcement','35 min, dernière séance relativement chargée avant le 35K.','Renfo'],['Jeu 24','Endurance + côtes courtes','45 min avec 8 × 30 s en côte, tonique mais jamais sprint.','Qualité'],['Sam 26','Trail facile','1 h 10–1 h 20, terrain vallonné.','Trail'],['Dim 27','Sortie longue réduite','1 h 50–2 h 10 facile, 500–700 m D+. Nutrition 65 g/h.','Longue']]},
{title:'28 sept. – 4 oct.',focus:'Allègement + 35 km. Le 35K est une séance-clé, pas un objectif à courir à bloc.',sessions:[['Lun 28','Repos','Mobilité 15 min.','Repos'],['Mar 29','Endurance','40–45 min facile + 4 × 20 s.','Facile'],['Mer 30','Activation renfo','20–25 min très légère, zéro courbature.','Renfo'],['Jeu 1','Rappel côtes','40 min total avec 3 × 3 min en côte RPE 6–7.','Qualité'],['Ven 2','Repos','Préparer matériel + nutrition.','Repos'],['Sam 3','Réveil','20 min très facile facultatif.','Facile'],['Dim 4','PETITES PYRÉNÉES — 35K / 1000 D+','RPE 5–6/10 jusqu’au km 25. 65 g/h. Descentes propres. Accélérer seulement si tout est vert.','Course']]},
{title:'5 – 11 oct.',focus:'Absorber le 35K. La récupération réussie vaut plus qu’une séance supplémentaire.',sessions:[['Lun 5','Repos complet','Marche douce, alimentation normale riche en protéines et glucides.','Repos'],['Mar 6','Repos ou 25 min très facile','Uniquement si jambes étonnamment bonnes.','Repos'],['Mer 7','Mobilité + gainage','20–25 min sans charge lourde.','Renfo'],['Jeu 8','Endurance','35–45 min facile si aucune douleur.','Facile'],['Sam 10','Footing','50–60 min facile + 4 lignes droites facultatives.','Facile'],['Dim 11','Trail facile','1 h 20–1 h 35, D+ modéré, aucune recherche de fatigue.','Trail']]},
{title:'12 – 18 oct.',focus:'Dernier rappel spécifique puis baisse du volume.',sessions:[['Lun 12','Repos','—','Repos'],['Mar 13','Endurance','45 min facile.','Facile'],['Mer 14','Renforcement entretien','25–30 min, 2 séries, aucune courbature recherchée.','Renfo'],['Jeu 15','Côtes longues — dernier rappel','15 min + 4 × 4 min RPE 7/10 + retour au calme.','Qualité'],['Sam 17','Footing facile','45–55 min + 5 × 20 s.','Facile'],['Dim 18','Trail court','1 h 15–1 h 30 facile. Dernier test matériel et nutrition, pas de grosse sortie.','Trail']]},
{title:'19 – 24 oct.',focus:'Affûtage final. On entretient la tonicité et on protège le sommeil.',sessions:[['Lun 19','Repos','Mobilité légère.','Repos'],['Mar 20','Endurance + activation','40 min facile + 4 × 20 s.','Facile'],['Mer 21','Repos','Préparer sacs, frontale, nutrition, vêtements.','Repos'],['Jeu 22','Réveil course','30–35 min avec 3 × 2 min RPE 6–7.','Qualité'],['Ven 23','Repos total','Hydratation normale, dîner tôt, coucher très anticipé.','Repos'],['Sam 24','TRAIL DES HÉRÉTIQUES — 63K / 2750 D+','Départ 04:00. Départ très contrôlé, nutrition dès 20 min, gestion musculaire des descentes.','Course']]}
];

function load(){let d={settings:{name:'Julien',initials:'JS',currentWeight:73,targetWeight:70,title:'Objectif Andorra 80K',subtitle:''},races:[],sessions:[],logs:[]};try{const x=JSON.parse(localStorage.getItem(KEY));if(x)d={...d,...x,settings:{...d.settings,...(x.settings||{})}}}catch(e){}d.races=d.races||[];d.logs=d.logs||[];d.sessions=d.sessions||[];racesSeed.forEach(r=>{let i=d.races.findIndex(x=>x.name===r.name||(x.date===r.date&&Math.abs((+x.distance||0)-r.distance)<2));if(i>=0)d.races[i]={...d.races[i],...r};else d.races.push({id:uid(),...r})});d.migrationCathares2026=true;localStorage.setItem(KEY,JSON.stringify(d));return d}
let data=load();
function fd(d){return new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}
function go(id,b){document.querySelectorAll('main section').forEach(s=>s.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function renderRaces(){let el=document.getElementById('raceCards');el.innerHTML='';[...data.races].sort((a,b)=>a.date.localeCompare(b.date)).forEach(r=>{if(r.date<'2026-08-29')return;const cls=r.distance>=60?'orange':r.distance>=35?'cyan':'';el.innerHTML+=`<div class="card"><div class="row"><div class="icon">${r.distance>=60?'🔥':r.distance>=35?'⛰️':'⚡️'}</div><div><h3>${r.name} — ${r.distance} km</h3><p>${fd(r.date)} · ${r.elevation||'—'} m D+<br>${r.role||''}</p><span class="tag ${cls}">${r.date==='2026-10-04'?'INSCRIT':r.distance>=60?'OBJECTIF':'PRÉPA'}</span></div></div></div>`})}
function renderWeeks(){const tabs=document.getElementById('weekTabs');tabs.innerHTML='';weeks.forEach((w,i)=>{const b=document.createElement('button');b.className='pill'+(i===0?' active':'');b.textContent=w.title;b.onclick=()=>selectWeek(i,b);tabs.appendChild(b)});selectWeek(0,tabs.firstChild)}
function selectWeek(i,b){document.querySelectorAll('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');const w=weeks[i];document.getElementById('weekSummary').textContent=w.focus;const c=document.getElementById('sessions');c.innerHTML='';w.sessions.forEach(s=>{let cls=s[3]==='Qualité'||s[3]==='Course'?'orange':s[3]==='Repos'?'gray':'';c.innerHTML+=`<div class="session"><div class="day">${s[0]}</div><div><h4>${s[1]}</h4><p>${s[2]}</p></div><span class="badge ${cls}">${s[3]}</span></div>`})}
function saveLog(){const o={id:uid(),date:logDate.value,weight:logWeight.value,sleep:logSleep.value,fatigue:logFatigue.value,pain:logPain.value,rpe:logRpe.value,notes:logNotes.value.trim()};if(!o.date)return alert('Date obligatoire.');data.logs.push(o);if(o.weight)data.settings.currentWeight=+o.weight;localStorage.setItem(KEY,JSON.stringify(data));renderTrack();analyse();alert('Relevé enregistré.')}
function renderTrack(){const arr=[...(data.logs||[])].sort((a,b)=>b.date.localeCompare(a.date));if(arr.length){const l=arr[0];mWeight.textContent=l.weight?Number(l.weight).toFixed(1).replace('.',','):((data.settings.currentWeight||73).toFixed(1).replace('.',','));mSleep.textContent=l.sleep||'—';mFatigue.textContent=l.fatigue||'—'}history.innerHTML=arr.slice(0,8).map(x=>`<div class="history-item"><b>${fd(x.date)}</b> · ${x.weight||'—'} kg · ${x.sleep||'—'} h · fatigue ${x.fatigue||'—'}/10 · douleur ${x.pain||'—'}/10</div>`).join('')||'<div class="history-item">Aucun relevé.</div>'}
function analyse(){const arr=[...(data.logs||[])].sort((a,b)=>b.date.localeCompare(a.date));if(!arr.length)return;const l=arr[0],s=+l.sleep,f=+l.fatigue,p=+l.pain;let msg='🟢 État favorable : conserve la séance prévue.';if(p>=3)msg='🔴 Douleur significative : pas d’intensité ni de descente rapide aujourd’hui. Repos, vélo doux ou marche, puis réévaluation.';else if(p>=2)msg='🟠 Douleur légère : terrain facile, séance réduite et aucune descente agressive.';else if(f>=7||(s&&s<6))msg='🔴 Récupération insuffisante : repos ou 30 min très faciles.';else if(f>=5||(s&&s<7))msg='🟠 Fatigue modérée : réduis la séance d’environ 20 % et supprime la fin intense.';homeAdvice.textContent=msg;coachAdvice.textContent=msg}
function countdown(){const now=new Date();const upcoming=[...racesSeed].filter(r=>new Date(r.date+'T23:59:00')>=now).sort((a,b)=>a.date.localeCompare(b.date));if(!upcoming.length)return;const r=upcoming[0],d=Math.max(0,Math.ceil((new Date(r.date+'T09:00:00')-now)/86400000));daysNext.textContent=d;nextLabel.textContent='jours avant '+r.name.replace('Trail des Petites Pyrénées — ','')}
function init(){logDate.value=new Date().toISOString().slice(0,10);renderRaces();renderWeeks();renderTrack();analyse();countdown()}
init();